hidden_size: [200, 250, 300]
drop_rate: [0.1, 0.25, 0.5]
learning_rate: [0.0002, 0.0005, 0.0007]
weight_decay: [0, 0.0001, 0.001]
l1_constant: [10, 20, 30, 40, 50]

max_trials: 25
batch_size: 5
n_fold: 5
epochs: 100
hpo_name: hpo_weighted